platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/awscli
    tag: latest
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
inputs:
  - name: govuk-infrastructure
    path: src
  - name: release
    optional: true
  - name: app-terraform-outputs
  - name: app-image
    optional: true
outputs:
  - name: task-definition-arn
params:
  AWS_REGION: eu-west-1
  ASSUME_ROLE_ARN: 'arn:aws:iam::430354129336:role/govuk-concourse-deployer'
  APPLICATION:
  VARIANT:
  REGISTRY: '172025368201.dkr.ecr.eu-west-1.amazonaws.com'
run:
  path: ./src/concourse/tasks/update-task-definition.sh
